# Generated by Django 2.2.28 on 2026-07-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height_m', models.FloatField(default=0.0, help_text='Height of the highest visible point above mean sea level, in metres. For a bridge this is the tower top; for a hill, the summit.')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Viewpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('eye_elevation_m', models.FloatField(default=1.6, help_text="Observer's eye height above mean sea level, in metres. Ground elevation plus roughly 1.6m for a standing adult.")),
                ('facing_bearing_deg', models.FloatField(default=0.0, help_text='Direction the viewpoint looks toward, in degrees clockwise from true north (0 = north, 90 = east).')),
                ('field_of_view_deg', models.FloatField(default=180.0, help_text='Width of the open view arc, centred on the facing bearing. Use 360 for an unobstructed all-round outlook.')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
